# -*- coding: utf-8 -*-
"""reverse a stack

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vZRsyGAKErnkzv9XAAVnuwauzEffbQa0
"""

#Reverse a stack
class Stack:
    def _init_(self):
        self.items = []

    def is_empty(self):
        return len(self.items) == 0

    def push(self, item):
        self.items.append(item)

    def pop(self):
        if not self.is_empty():
            return self.items.pop()
        return None

    def peek(self):
        if not self.is_empty():
            return self.items[-1]
        return None

    def size(self):
        return len(self.items)

    def _str_(self):
        return str(self.items)
def insert_at_bottom(stack, item):
    if stack.is_empty():
        stack.push(item)
    else:
        temp = stack.pop()
        insert_at_bottom(stack, item)
        stack.push(temp)
def reverse_stack(stack):
    if not stack.is_empty():
        temp = stack.pop()
        reverse_stack(stack)
        insert_at_bottom(stack, temp)



if _name_ == "_main_":
    stack = Stack()
    stack.push(1)
    stack.push(2)
    stack.push(3)
    stack.push(4)

    print("Original Stack:", stack)
    reverse_stack(stack)
    print("Reversed Stack:", stack)

