# -*- coding: utf-8 -*-
"""Sorting the stack in Descending order

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vZRsyGAKErnkzv9XAAVnuwauzEffbQa0
"""

class Stack:
    def _init_(self):
        self.items = []

    def is_empty(self):
        return len(self.items) == 0

    def push(self, item):
        self.items.append(item)

    def pop(self):
        if not self.is_empty():
            return self.items.pop()
        return None

    def peek(self):
        if not self.is_empty():
            return self.items[-1]
        return None

    def size(self):
        return len(self.items)

    def _str_(self):
        return str(self.items)


def sort_stack(stack):
    temp_stack = Stack()

    while not stack.is_empty():
        current_element = stack.pop()
        while not temp_stack.is_empty() and temp_stack.peek() > current_element:
            stack.push(temp_stack.pop())
        temp_stack.push(current_element)
    while not temp_stack.is_empty():
        stack.push(temp_stack.pop())

    return stack



stack = Stack()
stack.push(34)
stack.push(3)
stack.push(31)
stack.push(98)
stack.push(92)
stack.push(23)

print("Original Stack:", stack)
sorted_stack = sort_stack(stack)
print("Sorted Stack (Descending Order):", sorted_stack)

